apiVersion: v1
kind: Service
metadata:
  name: messaging
  labels:
    app: amq-interconnect
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: qdr-external-cert
spec:
  ports:
  - port: 5672
    name: amqp
  - port: 55672
    name: inter-router
  selector:
    type: qdrouterd
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: amq-interconnect
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: amq-interconnect
        version: v1
        type: qdrouterd
    spec:
      containers:
      - name: amq-interconnect
        env:
        - name: AMQ_LOCATION_KEY
          value: AZR
        image: tedross/qpid-dispatch-router:1.2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5672
          protocol: TCP
        volumeMounts:
        - name: qdr-config
          mountPath: /etc/qpid-dispatch
        - name: internal-certs
          readOnly: true
          mountPath: /etc/qpid-dispatch-certs/internal
      volumes:
      - name: qdr-config
        configMap:
          name: qdr-config
      - name: internal-certs
        secret:
          secretName: qdr-internal-cert
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: amq-interconnect
  name: inter-router
spec:
  host: inter-router-demo2-amq.${AZURE_SUFFIX}
  port:
    targetPort: inter-router
  tls:
    termination: passthrough
  to:
    kind: Service
    name: messaging
    weight: 100
  wildcardPolicy: None
